### ISSUE TITLE
Can't compile this on Linux

### ISSUE THREAD

**Issue by Higher08** [SDGGiesbrecht/SDGCornerstone#454]
### Description

This project don't compiles on Linux (Ubuntu)
### Demonstration

`/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:29:31: error: 'Float80' is unavailable: Float80 is not available on target platform.
  public typealias FloatMax = Float80
                              ^~~~~~~
Swift.Float80:2:23: note: 'Float80' has been explicitly marked unavailable here
@frozen public struct Float80 {
                      ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:322:22: error: type alias 'Vector' references itself
    public typealias Vector = Stride
                     ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: note: through reference here
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: note: through reference here
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:322:31: note: while resolving type 'Stride'
    public typealias Vector = Stride
                              ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:322:22: error: type alias 'Vector' references itself
    public typealias Vector = Stride
                     ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:322:22: note: through reference here
    public typealias Vector = Stride
                     ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: note: through reference here
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: note: through reference here
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:322:31: note: while resolving type 'Stride'
    public typealias Vector = Stride
                              ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:322:22: error: type alias 'Vector' references itself
    public typealias Vector = Stride
                     ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: note: through reference here
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: note: through reference here
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:322:31: note: while resolving type 'Stride'
    public typealias Vector = Stride
                              ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:326:26: error: 'Float80' is unavailable: Float80 is not available on target platform.
    public static let e: Float80 = 0x1.5BF0A8B145769535p1
                         ^~~~~~~
Swift.Float80:2:23: note: 'Float80' has been explicitly marked unavailable here
@frozen public struct Float80 {
                      ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'BinaryFloatingPoint'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'CustomDebugStringConvertible'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'LosslessStringConvertible'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/WholeArithmetic.swift:210:21: note: candidate has non-matching type 'U'
  @inlinable public init<U: UIntFamily>(_ uInt: U) {
                    ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/IntegralArithmetic.swift:33:21: note: candidate has non-matching type 'I'
  @inlinable public init<I: IntFamily>(_ int: I) {
                    ^
Swift.BinaryFloatingPoint:5:23: note: candidate has non-matching type 'Source'
    @inlinable public init<Source>(_ value: Source) where Source : BinaryFloatingPoint
                      ^
Swift.BinaryFloatingPoint:3:23: note: candidate would match if 'Float80.RawSignificand' conformed to 'FixedWidthInteger'
    @inlinable public init<Source>(_ value: Source) where Source : BinaryInteger
                      ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'FloatingPoint'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'ExpressibleByFloatLiteral'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
Swift.ExpressibleByFloatLiteral:2:20: note: unable to infer associated type 'FloatLiteralType' for protocol 'ExpressibleByFloatLiteral'
    associatedtype FloatLiteralType : _ExpressibleByBuiltinFloatLiteral
                   ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/RationalArithmetic.swift:114:21: note: candidate would match and infer 'FloatLiteralType' = 'FloatMax' (aka 'Float80') if 'FloatMax' (aka 'Float80') conformed to '_ExpressibleByBuiltinFloatLiteral'
  @inlinable public init(floatLiteral: FloatMax) {
                    ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'CustomStringConvertible'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'RealArithmetic'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:152:33: note: candidate would match if 'Float80' conformed to 'ElementaryFunctions'
  @inlinable public static func sin(_ angle: Angle<Self>) -> Self {
                                ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:168:33: note: candidate would match if 'Float80' conformed to 'ElementaryFunctions'
  @inlinable public static func arctan(_ tangent: Self) -> Angle<Self> {
                                ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'Strideable'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
Swift.Strideable:2:20: note: unable to infer associated type 'Stride' for protocol 'Strideable'
    associatedtype Stride : Comparable, SignedNumeric
                   ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/OneDimensionalPoint.swift:59:26: note: candidate can not infer 'Stride' = 'Float80.Vector' because 'Float80.Vector' is not a nominal type and so can't conform to 'Comparable'
  @inlinable public func distance(to other: Self) -> Vector {
                         ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/OneDimensionalPoint.swift:51:26: note: candidate can not infer 'Stride' = 'Float80.Vector' because 'Float80.Vector' is not a nominal type and so can't conform to 'Comparable'
  @inlinable public func advanced(by n: Vector) -> Self {
                         ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: extension outside of file declaring struct 'Float80' prevents automatic synthesis of 'hash(into:)' for protocol 'Hashable'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
Swift.Float80:2:23: note: type declared here
@frozen public struct Float80 {
                      ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'Numeric'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
Swift.BinaryFloatingPoint:6:23: note: candidate has non-matching type '(exactly: Source)' [with Magnitude = Float80]
    @inlinable public init?<Source>(exactly value: Source) where Source : BinaryFloatingPoint
                      ^
Swift.BinaryFloatingPoint:4:23: note: candidate would match if 'Float80.RawSignificand' conformed to 'FixedWidthInteger'
    @inlinable public init?<Source>(exactly value: Source) where Source : BinaryInteger
                      ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'WholeArithmetic'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/RationalArithmetic.swift:90:33: note: candidate has non-matching type '<Self, R> (in: Range<Self>, using: inout R) -> Self'
  @inlinable public static func random<R>(in range: Range<Self>, using generator: inout R) -> Self
                                ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/RationalArithmetic.swift:137:33: note: candidate has non-matching type '<Self, R> (in: Range<Self>, using: inout R) -> Self'
  @inlinable public static func random<R>(in range: Range<Self>, using generator: inout R) -> Self
                                ^
Swift.BinaryFloatingPoint:2:35: note: candidate has non-matching type '<Self, T> (in: Range<Self>, using: inout T) -> Self'
    @inlinable public static func random<T>(in range: Range<Self>, using generator: inout T) -> Self where T : RandomNumberGenerator
                                  ^
Swift.BinaryFloatingPoint:4:35: note: candidate would match if 'Float80.RawSignificand' conformed to 'FixedWidthInteger'
    @inlinable public static func random<T>(in range: ClosedRange<Self>, using generator: inout T) -> Self where T : RandomNumberGenerator
                                  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'FixedScaleOneDimensionalPoint'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:3: error: type 'Float80' does not conform to protocol 'PointProtocol'
  extension Float80: Decodable, Encodable, FloatFamily {
  ^
Swift.BinaryFloatingPoint:2:20: note: protocol requires nested type 'RawSignificand'; do you want to add it?
    associatedtype RawSignificand : UnsignedInteger
                   ^
Swift.BinaryFloatingPoint:3:20: note: protocol requires nested type 'RawExponent'; do you want to add it?
    associatedtype RawExponent : UnsignedInteger
                   ^
Swift.CustomDebugStringConvertible:2:9: note: protocol requires property 'debugDescription' with type 'String'
    var debugDescription: String { get }
        ^
Swift.LosslessStringConvertible:2:5: note: protocol requires initializer 'init(_:)' with type 'String'
    init?(_ description: String)
    ^
Swift.FloatingPoint:2:20: note: protocol requires nested type 'Exponent'; do you want to add it?
    associatedtype Exponent : SignedInteger
                   ^
Swift.CustomStringConvertible:2:9: note: protocol requires property 'description' with type 'String'
    var description: String { get }
        ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/RealArithmetic.swift:117:15: note: protocol requires function 'sin' with type '(Angle<Float80>) -> Float80'
  static func sin(_ angle: Angle<Self>) -> Self
              ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/RealArithmetic.swift:183:15: note: protocol requires function 'arctan' with type '(Float80) -> Angle<Float80>'
  static func arctan(_ tangent: Self) -> Angle<Self>
              ^
Swift.Numeric:2:5: note: protocol requires initializer 'init(exactly:)' with type '(exactly: T)'
    init?<T>(exactly source: T) where T : BinaryInteger
    ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/WholeArithmetic.swift:204:15: note: protocol requires function 'random(in:using:)' with type '<R> (in: ClosedRange<Float80>, using: inout R) -> Float80'
  static func random<R>(in range: ClosedRange<Self>, using generator: inout R) -> Self
              ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Numeric Protocols/PointProtocol.swift:23:18: note: protocol requires nested type 'Vector'; do you want to add it?
  associatedtype Vector: Negatable
                 ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:305:13: error: 'Float80' is unavailable: Float80 is not available on target platform.
  extension Float80: Decodable, Encodable, FloatFamily {
            ^~~~~~~
Swift.Float80:2:23: note: 'Float80' has been explicitly marked unavailable here
@frozen public struct Float80 {
                      ^
/home/ubuntu/stalker/.build/checkouts/SDGCornerstone/Sources/SDGMathematics/Float.swift:329:19: error: type 'Float80' has no member 'log10'
      return Self.log10(antilogarithm)
             ~~~~ ^~~~~`

**Comment by SDGGiesbrecht** [comment]
Thank you for reporting this.

This issue must be more specific that just “Linux”, as all the platforms listed in the read‐me are tested before any commit is merged.

- What version (or commit) of SDGCornerstone are you attempting to build?
- What version of Swift are you using to build it?
- Which flavour and version of Linux are you using? (Ubuntu 16, 18, or 20; CentOS 7 or 8; or Amazon Linux 2?)
- What architecture are you using?

**Comment by Higher08** [comment]
1. Latest release
2. Swift 5.5.1
3. Ubuntu Server 20.04
4. Arm-64

**Comment by Higher08** [comment]
It looks like Float80 isn't available on ARM. Maybe this is source of all errors?

**Comment by SDGGiesbrecht** [comment]
arm64 is likely the issue. I do not see any toolchain for it in [Swift’s official download list](https://www.swift.org/download/#trunk-development-main) (and SwiftPM does not officially cross‐compile yet). Are you using a custom toolchain?

I will look at the Standard Library source to figure out how `Float80` is gated for unofficial platforms and see what I can do. But if those source files have been patched in any way in your toolchain, even that may not help.

**Comment by Higher08** [comment]
I use this swift arm builds
https://github.com/futurejones/swift-arm64
Also, Float80 isn't available on real iphone (not simulator)

> In a thread on the older forums, one of the Apple engineers stated that the reason Float80 is only available on OS X and simulated iOS (not on iOS hardware) is because it isn't built in to the ARM processors.



It doesn't sound like they are planning to put much work into Float80 at this point, if it isn't even going to to be availble on iOS devices. Since it It doesn't already have the right methods to conform to the protocol on OS X, it might not be worth the effort to them to make it conform.

**Comment by Higher08** [comment]
And I think that this problem will occur at Apple Silicone

**Comment by SDGGiesbrecht** [comment]
Please try from the temporary [`arm64` branch](https://github.com/SDGGiesbrecht/SDGCornerstone/pull/455), and let me know if it works, or if other things need to be adjusted as well.

The architecture differences for iOS, macOS and any Xcode‐related platform have been properly handled for a long time. Xcode’s ability to build for “all architectures” flagged the problems about as soon as the new architecture was released. But SwiftPM has no equivalent, so differences between Linux architectures escape notice much more easily.

**Comment by Higher08** [comment]
It added more errors)
https://gist.github.com/Higher08/ec6b991914be1123131bb9c93e0a87f0

**Comment by Higher08** [comment]
Adding condition for platform here https://github.com/SDGGiesbrecht/SDGCornerstone/blob/arm64/Sources/SDGMathematics/Float.swift#L22
may be helpful

**Comment by Higher08** [comment]
My fork is working, and you can add the same changes. I don't think that one line needs PR

**Comment by SDGGiesbrecht** [comment]
Based on your comments, I believe `master` should work now.

If you can confirm that it does, I will tag an 8.0.1 release.

**Comment by SDGGiesbrecht** [comment]
The adjustments discussed here are in 8.0.1.

Since I have not found a way to test arm64 in CI, it remains only unofficially supported. As development moves on, the intention is that any problems that get reported will be fixed promptly. However, without CI, it is possible that accidental breakages could find their way unnoticed even into patch releases. Therefore, anything that intends to support arm64 and depends on SDGCornerstone is advised to do so by specifying the version with `.exact(...)` instead of `from: ...`.
